export type AreaCounty = "Pinal" | "Maricopa" | "Navajo" | "Apache";

export type ZipEntry = {
  zip: string;
  city: string;
  county: AreaCounty;
};

// Curated list of ZIP codes inside FFI's currently-served areas.
// Not exhaustive — used to confirm coverage and recognize the city/county.
export const servedZips: ZipEntry[] = [
  // Pinal
  { zip: "85122", city: "Casa Grande", county: "Pinal" },
  { zip: "85193", city: "Casa Grande", county: "Pinal" },
  { zip: "85194", city: "Casa Grande", county: "Pinal" },
  { zip: "85128", city: "Coolidge", county: "Pinal" },
  { zip: "85132", city: "Florence", county: "Pinal" },
  { zip: "85117", city: "Apache Junction", county: "Pinal" },
  { zip: "85118", city: "Apache Junction", county: "Pinal" },
  { zip: "85119", city: "Apache Junction", county: "Pinal" },
  { zip: "85120", city: "Apache Junction", county: "Pinal" },
  { zip: "85123", city: "Arizona City", county: "Pinal" },
  { zip: "85138", city: "Maricopa", county: "Pinal" },
  { zip: "85139", city: "Maricopa", county: "Pinal" },
  { zip: "85140", city: "San Tan Valley", county: "Pinal" },
  { zip: "85142", city: "Queen Creek", county: "Pinal" },
  { zip: "85143", city: "San Tan Valley", county: "Pinal" },
  { zip: "85145", city: "Red Rock", county: "Pinal" },
  { zip: "85172", city: "Stanfield", county: "Pinal" },

  // Maricopa
  { zip: "85003", city: "Phoenix", county: "Maricopa" },
  { zip: "85004", city: "Phoenix", county: "Maricopa" },
  { zip: "85006", city: "Phoenix", county: "Maricopa" },
  { zip: "85007", city: "Phoenix", county: "Maricopa" },
  { zip: "85008", city: "Phoenix", county: "Maricopa" },
  { zip: "85009", city: "Phoenix", county: "Maricopa" },
  { zip: "85013", city: "Phoenix", county: "Maricopa" },
  { zip: "85014", city: "Phoenix", county: "Maricopa" },
  { zip: "85015", city: "Phoenix", county: "Maricopa" },
  { zip: "85016", city: "Phoenix", county: "Maricopa" },
  { zip: "85017", city: "Phoenix", county: "Maricopa" },
  { zip: "85018", city: "Phoenix", county: "Maricopa" },
  { zip: "85019", city: "Phoenix", county: "Maricopa" },
  { zip: "85020", city: "Phoenix", county: "Maricopa" },
  { zip: "85021", city: "Phoenix", county: "Maricopa" },
  { zip: "85022", city: "Phoenix", county: "Maricopa" },
  { zip: "85023", city: "Phoenix", county: "Maricopa" },
  { zip: "85024", city: "Phoenix", county: "Maricopa" },
  { zip: "85027", city: "Phoenix", county: "Maricopa" },
  { zip: "85028", city: "Phoenix", county: "Maricopa" },
  { zip: "85029", city: "Phoenix", county: "Maricopa" },
  { zip: "85031", city: "Phoenix", county: "Maricopa" },
  { zip: "85032", city: "Phoenix", county: "Maricopa" },
  { zip: "85033", city: "Phoenix", county: "Maricopa" },
  { zip: "85034", city: "Phoenix", county: "Maricopa" },
  { zip: "85035", city: "Phoenix", county: "Maricopa" },
  { zip: "85037", city: "Phoenix", county: "Maricopa" },
  { zip: "85040", city: "Phoenix", county: "Maricopa" },
  { zip: "85041", city: "Phoenix", county: "Maricopa" },
  { zip: "85042", city: "Phoenix", county: "Maricopa" },
  { zip: "85043", city: "Phoenix", county: "Maricopa" },
  { zip: "85044", city: "Phoenix", county: "Maricopa" },
  { zip: "85045", city: "Phoenix", county: "Maricopa" },
  { zip: "85048", city: "Phoenix", county: "Maricopa" },
  { zip: "85050", city: "Phoenix", county: "Maricopa" },
  { zip: "85051", city: "Phoenix", county: "Maricopa" },
  { zip: "85053", city: "Phoenix", county: "Maricopa" },
  { zip: "85054", city: "Phoenix", county: "Maricopa" },
  { zip: "85083", city: "Phoenix", county: "Maricopa" },
  { zip: "85085", city: "Phoenix", county: "Maricopa" },
  { zip: "85086", city: "Phoenix", county: "Maricopa" },
  { zip: "85201", city: "Mesa", county: "Maricopa" },
  { zip: "85202", city: "Mesa", county: "Maricopa" },
  { zip: "85203", city: "Mesa", county: "Maricopa" },
  { zip: "85204", city: "Mesa", county: "Maricopa" },
  { zip: "85205", city: "Mesa", county: "Maricopa" },
  { zip: "85206", city: "Mesa", county: "Maricopa" },
  { zip: "85207", city: "Mesa", county: "Maricopa" },
  { zip: "85208", city: "Mesa", county: "Maricopa" },
  { zip: "85209", city: "Mesa", county: "Maricopa" },
  { zip: "85210", city: "Mesa", county: "Maricopa" },
  { zip: "85212", city: "Mesa", county: "Maricopa" },
  { zip: "85213", city: "Mesa", county: "Maricopa" },
  { zip: "85215", city: "Mesa", county: "Maricopa" },
  { zip: "85224", city: "Chandler", county: "Maricopa" },
  { zip: "85225", city: "Chandler", county: "Maricopa" },
  { zip: "85226", city: "Chandler", county: "Maricopa" },
  { zip: "85248", city: "Chandler", county: "Maricopa" },
  { zip: "85249", city: "Chandler", county: "Maricopa" },
  { zip: "85233", city: "Gilbert", county: "Maricopa" },
  { zip: "85234", city: "Gilbert", county: "Maricopa" },
  { zip: "85295", city: "Gilbert", county: "Maricopa" },
  { zip: "85296", city: "Gilbert", county: "Maricopa" },
  { zip: "85297", city: "Gilbert", county: "Maricopa" },
  { zip: "85298", city: "Gilbert", county: "Maricopa" },
  { zip: "85251", city: "Scottsdale", county: "Maricopa" },
  { zip: "85254", city: "Scottsdale", county: "Maricopa" },
  { zip: "85257", city: "Scottsdale", county: "Maricopa" },
  { zip: "85258", city: "Scottsdale", county: "Maricopa" },
  { zip: "85281", city: "Tempe", county: "Maricopa" },
  { zip: "85282", city: "Tempe", county: "Maricopa" },
  { zip: "85283", city: "Tempe", county: "Maricopa" },
  { zip: "85284", city: "Tempe", county: "Maricopa" },
  { zip: "85301", city: "Glendale", county: "Maricopa" },
  { zip: "85302", city: "Glendale", county: "Maricopa" },
  { zip: "85303", city: "Glendale", county: "Maricopa" },
  { zip: "85304", city: "Glendale", county: "Maricopa" },
  { zip: "85305", city: "Glendale", county: "Maricopa" },
  { zip: "85306", city: "Glendale", county: "Maricopa" },
  { zip: "85307", city: "Glendale", county: "Maricopa" },
  { zip: "85308", city: "Glendale", county: "Maricopa" },
  { zip: "85335", city: "El Mirage", county: "Maricopa" },
  { zip: "85339", city: "Laveen", county: "Maricopa" },
  { zip: "85345", city: "Peoria", county: "Maricopa" },
  { zip: "85351", city: "Sun City", county: "Maricopa" },
  { zip: "85353", city: "Tolleson", county: "Maricopa" },
  { zip: "85354", city: "Tonopah", county: "Maricopa" },
  { zip: "85373", city: "Sun City", county: "Maricopa" },
  { zip: "85374", city: "Surprise", county: "Maricopa" },
  { zip: "85375", city: "Sun City West", county: "Maricopa" },
  { zip: "85379", city: "Surprise", county: "Maricopa" },
  { zip: "85382", city: "Peoria", county: "Maricopa" },
  { zip: "85383", city: "Peoria", county: "Maricopa" },
  { zip: "85387", city: "Surprise", county: "Maricopa" },
  { zip: "85388", city: "Surprise", county: "Maricopa" },
  { zip: "85396", city: "Buckeye", county: "Maricopa" },

  // Navajo
  { zip: "85901", city: "Show Low", county: "Navajo" },
  { zip: "85902", city: "Show Low", county: "Navajo" },
  { zip: "85911", city: "Cibecue", county: "Navajo" },
  { zip: "85912", city: "White Mountain Lake", county: "Navajo" },
  { zip: "85929", city: "Lakeside", county: "Navajo" },
  { zip: "85933", city: "Overgaard", county: "Navajo" },
  { zip: "85935", city: "Pinetop", county: "Navajo" },
  { zip: "85937", city: "Snowflake", county: "Navajo" },
  { zip: "85939", city: "Taylor", county: "Navajo" },
  { zip: "85941", city: "Whiteriver", county: "Navajo" },

  // Apache
  { zip: "85920", city: "Alpine", county: "Apache" },
  { zip: "85924", city: "Concho", county: "Apache" },
  { zip: "85925", city: "Eagar", county: "Apache" },
  { zip: "85928", city: "Heber", county: "Apache" },
  { zip: "85932", city: "Nutrioso", county: "Apache" },
  { zip: "85936", city: "St. Johns", county: "Apache" },
  { zip: "85938", city: "Springerville", county: "Apache" },
  { zip: "85940", city: "Vernon", county: "Apache" },
];

export const servedZipSet = new Set(servedZips.map((z) => z.zip));
